var N = null;var sourcesIndex = {};
sourcesIndex["nimbus_consensus"] = {"name":"","files":["import_queue.rs","lib.rs","manual_seal.rs"]};
sourcesIndex["nimbus_primitives"] = {"name":"","files":["digests.rs","inherents.rs","lib.rs"]};
sourcesIndex["pallet_aura_style_filter"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_author_inherent"] = {"name":"","files":["exec.rs","lib.rs"]};
sourcesIndex["pallet_author_slot_filter"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pallet_template"] = {"name":"","files":["lib.rs"]};
sourcesIndex["parachain_collator"] = {"name":"","files":["chain_spec.rs","cli.rs","command.rs","main.rs","rpc.rs","service.rs"]};
sourcesIndex["parachain_template_runtime"] = {"name":"","files":["lib.rs","pallet_account_set.rs"]};
createSourceSidebar();
